### ISSUE TITLE
unclear on what the format the value for version_control_system_organization should be for personal github

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/alz-terraform-accelerator#68]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

We are using the Complete Starter module

### Description

**Describe the bug**
Get the following error. Documentation is unclear on what the format the value for version_control_system_organization should be.

Plan: 41 to add, 0 to change, 0 to destroy.
╷
│ Error: GET https://api.github.com/orgs/ashley-kainos: 404 Not Found []
│
│   with module.github.data.github_organization.alz,
│   on ..\modules\github\data.tf line 1, in data "github_organization" "alz":
│    1: data "github_organization" "alz" {

**Steps to Reproduce**

follow steps until you get to Phase 2 then follow 2.2.2 Github and the plan run and the error come up

1. step 1
2. step 2
3. you get it...

**Comment by jaredfholgate** [comment]
Hi @ashley-kainos. Agreed that the documentation is not clear. We have an existing issue to tackle this here:  #36. We are looking to tackle this ASAP. We initially thought we could support both self hosted and SaaS versions of GitHub and Azure DevOps with this accelerator, hence the ability to supply a FQDN. However, we are unable to support self hosted due to a number of limitations, so we will remove the ability to supply an FQDN and make it clear in the documentation that we only support SaaS and exactly what should be entered into this field.

I think the actual bug you are hitting is regarding support for personal GitHub organisations though and that issue has been raised here: #34. Again we want to resolve this ASAP. We should be able to fix this. In the meantime use can use a free organisation as long as it is not a personal one.
